(function (root) {
  root.HOMONYM_DRAFT_PUZZLES = [
    {
      id: 'draft-001',
      clue: 'loathsome test tube',
      displayAnswer: 'vile vial',
      answerWords: ['vile', 'vial'],
      aliases: ['vile-vial'],
      explanation: ['vile = loathsome', 'vial = test tube / small lab bottle'],
      difficulty: 'easy',
      status: 'reviewed',
      notes: 'Still one of the cleanest model entries.',
    },
    {
      id: 'draft-002',
      clue: 'lazy golden calf',
      displayAnswer: 'idle idol',
      answerWords: ['idle', 'idol'],
      aliases: ['idle-idol'],
      explanation: ['idle = lazy', 'idol = golden calf / object of worship'],
      difficulty: 'easy',
      status: 'reviewed',
      notes: 'Strong flagship example for the core mechanic.',
    },
    {
      id: 'draft-003',
      clue: 'thief of shepherd\'s tools',
      displayAnswer: 'crook crook',
      answerWords: ['crook', 'crook'],
      aliases: [],
      explanation: ['crook = thief / criminal', 'crook = shepherd\'s hooked staff'],
      difficulty: 'hard',
      status: 'prototype',
      notes: 'Funny, but repeated-word answers should stay rare.',
    },
    {
      id: 'draft-004',
      clue: 'sad sunrise',
      displayAnswer: 'mourning morning',
      answerWords: ['mourning', 'morning'],
      aliases: [],
      explanation: ['mourning = grief / sadness', 'morning = sunrise time'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Very legible; phrase is a little literary but still natural enough.',
    },
    {
      id: 'draft-005',
      clue: 'seafaring belly button',
      displayAnswer: 'naval navel',
      answerWords: ['naval', 'navel'],
      aliases: [],
      explanation: ['naval = related to the navy', 'navel = belly button'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'More precise than the earlier draft, though still somewhat transparent.',
    },
    {
      id: 'draft-006',
      clue: 'only spirit',
      displayAnswer: 'sole soul',
      answerWords: ['sole', 'soul'],
      aliases: [],
      explanation: ['sole = only', 'soul = spirit / being'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Clean and intuitive.',
    },
    {
      id: 'draft-007',
      clue: 'beloved buck',
      displayAnswer: 'dear deer',
      answerWords: ['dear', 'deer'],
      aliases: [],
      explanation: ['dear = beloved', 'deer = woodland animal'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Cleaner than the earlier invalid draft, though slightly storybook in tone.',
    },
    {
      id: 'draft-008',
      clue: 'faint seven days',
      displayAnswer: 'weak week',
      answerWords: ['weak', 'week'],
      aliases: [],
      explanation: ['weak = faint / lacking strength', 'week = seven days'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Simple and fair, though likely too easy for top-tier daily play.',
    },
    {
      id: 'draft-009',
      clue: 'ordinary jet',
      displayAnswer: 'plain plane',
      answerWords: ['plain', 'plane'],
      aliases: [],
      explanation: ['plain = simple / unadorned', 'plane = aircraft'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Cleaner than the original, but still on the easy side.',
    },
    {
      id: 'draft-010',
      clue: 'sequential breakfast grain',
      displayAnswer: 'serial cereal',
      answerWords: ['serial', 'cereal'],
      aliases: [],
      explanation: ['serial = repeated / sequential', 'cereal = breakfast grain'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Intentionally absurdist, but now cleaner.',
    },
    {
      id: 'draft-011',
      clue: 'main rule',
      displayAnswer: 'principal principle',
      answerWords: ['principal', 'principle'],
      aliases: [],
      explanation: ['principal = chief / main', 'principle = belief / rule'],
      difficulty: 'hard',
      status: 'draft',
      notes: 'Sharper than the earlier draft but still conceptually abstract.',
    },
    {
      id: 'draft-012',
      clue: 'junior prospector',
      displayAnswer: 'minor miner',
      answerWords: ['minor', 'miner'],
      aliases: [],
      explanation: ['minor = junior / underage', 'miner = one who digs ore'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Very clean and concrete.',
    },
    {
      id: 'draft-013',
      clue: 'middle trash',
      displayAnswer: 'waist waste',
      answerWords: ['waist', 'waste'],
      aliases: [],
      explanation: ['waist = waistline / middle of the body', 'waste = garbage / refuse'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Cleaner than the earlier version, though still fairly transparent.',
    },
    {
      id: 'draft-014',
      clue: 'masculine letters',
      displayAnswer: 'male mail',
      answerWords: ['male', 'mail'],
      aliases: ['mailed male'],
      explanation: ['male = masculine', 'mail = letters / post'],
      difficulty: 'hard',
      status: 'draft',
      notes: 'Improved, but still one of the weaker entries in the set.',
    },
    {
      id: 'draft-015',
      clue: 'permitted audibly',
      displayAnswer: 'allowed aloud',
      answerWords: ['allowed', 'aloud'],
      aliases: [],
      explanation: ['allowed = permitted', 'aloud = out loud'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Still straightforward, but less giveaway than the stock gloss.',
    },
    {
      id: 'draft-016',
      clue: 'viewing location',
      displayAnswer: 'sight site',
      answerWords: ['sight', 'site'],
      aliases: [],
      explanation: ['sight = vision', 'site = place / location'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'More concrete than the earlier draft, but still a mid-tier entry.',
    },
    {
      id: 'draft-017',
      clue: 'blossom baking staple',
      displayAnswer: 'flower flour',
      answerWords: ['flower', 'flour'],
      aliases: [],
      explanation: ['flower = blossom', 'flour = milled grain / baking ingredient'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Corrected the flour explanation and tightened the clue.',
    },
    {
      id: 'draft-018',
      clue: 'couple fruit',
      displayAnswer: 'pair pear',
      answerWords: ['pair', 'pear'],
      aliases: [],
      explanation: ['pair = couple', 'pear = fruit'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Excellent for a beginner pack.',
    },
    {
      id: 'draft-019',
      clue: 'armored evening',
      displayAnswer: 'knight night',
      answerWords: ['knight', 'night'],
      aliases: [],
      explanation: ['knight = armored warrior', 'night = evening / darkness'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Simple and vivid, though slightly storybook in tone.',
    },
    {
      id: 'draft-020',
      clue: 'store corridor island',
      displayAnswer: 'aisle isle',
      answerWords: ['aisle', 'isle'],
      aliases: [],
      explanation: ['aisle = store corridor / passage', 'isle = island'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Clean sound pair; clue is compact but slightly clipped.',
    },
    {
      id: 'draft-021',
      clue: 'alloy heist',
      displayAnswer: 'steel steal',
      answerWords: ['steel', 'steal'],
      aliases: [],
      explanation: ['steel = alloy metal', 'steal = commit a heist / theft'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Strong sound pair with a vivid clue surface.',
    },
    {
      id: 'draft-022',
      clue: 'prompt line',
      displayAnswer: 'cue queue',
      answerWords: ['cue', 'queue'],
      aliases: [],
      explanation: ['cue = prompt / signal', 'queue = line / waiting row'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Compact and elegant, with uncommon spelling carrying some difficulty.',
    },
    {
      id: 'draft-023',
      clue: 'coin aroma',
      displayAnswer: 'cent scent',
      answerWords: ['cent', 'scent'],
      aliases: [],
      explanation: ['cent = coin worth one hundredth of a dollar', 'scent = aroma / smell'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Classic pair and very fair.',
    },
    {
      id: 'draft-024',
      clue: 'story appendage',
      displayAnswer: 'tale tail',
      answerWords: ['tale', 'tail'],
      aliases: [],
      explanation: ['tale = story', 'tail = appendage'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Simple and playful.',
    },
    {
      id: 'draft-025',
      clue: 'prison trade',
      displayAnswer: 'cell sell',
      answerWords: ['cell', 'sell'],
      aliases: [],
      explanation: ['cell = prison room', 'sell = make a trade / sale'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Good distinct meanings, though the phrase is a little blunt.',
    },
    {
      id: 'draft-026',
      clue: 'harness center',
      displayAnswer: 'yoke yolk',
      answerWords: ['yoke', 'yolk'],
      aliases: [],
      explanation: ['yoke = harness / wooden crosspiece', 'yolk = egg center'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Memorable and nicely concrete.',
    },
    {
      id: 'draft-027',
      clue: 'brawny shellfish',
      displayAnswer: 'muscle mussel',
      answerWords: ['muscle', 'mussel'],
      aliases: [],
      explanation: ['muscle = brawny tissue / strength', 'mussel = edible shellfish'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Fun, vivid, and slightly tongue-twisting.',
    },
    {
      id: 'draft-028',
      clue: 'seed officer',
      displayAnswer: 'kernel colonel',
      answerWords: ['kernel', 'colonel'],
      aliases: [],
      explanation: ['kernel = seed core', 'colonel = military officer'],
      difficulty: 'hard',
      status: 'draft',
      notes: 'A good hard entry driven by irregular spelling.',
    },
    {
      id: 'draft-029',
      clue: 'ticket carnival',
      displayAnswer: 'fare fair',
      answerWords: ['fare', 'fair'],
      aliases: [],
      explanation: ['fare = ticket cost / travel price', 'fair = carnival / public festival'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Pleasant clue surface and decent differentiation.',
    },
    {
      id: 'draft-030',
      clue: 'stage witnessed',
      displayAnswer: 'scene seen',
      answerWords: ['scene', 'seen'],
      aliases: [],
      explanation: ['scene = stage setting / tableau', 'seen = witnessed / observed'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Not bad, though more abstract than the strongest clues.',
    },
    {
      id: 'draft-031',
      clue: 'chapel change',
      displayAnswer: 'altar alter',
      answerWords: ['altar', 'alter'],
      aliases: [],
      explanation: ['altar = chapel focal table', 'alter = change / modify'],
      difficulty: 'hard',
      status: 'draft',
      notes: 'Strong hard-mode candidate with clean clueing.',
    },
    {
      id: 'draft-032',
      clue: 'mineral paddle',
      displayAnswer: 'ore oar',
      answerWords: ['ore', 'oar'],
      aliases: [],
      explanation: ['ore = mineral rock', 'oar = paddle for rowing'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Short and highly legible.',
    },
    {
      id: 'draft-033',
      clue: 'bunny follicles',
      displayAnswer: 'hare hair',
      answerWords: ['hare', 'hair'],
      aliases: [],
      explanation: ['hare = bunny / rabbit-like animal', 'hair = follicles / strands'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Playful and concrete.',
    },
    {
      id: 'draft-034',
      clue: 'labyrinth corn',
      displayAnswer: 'maze maize',
      answerWords: ['maze', 'maize'],
      aliases: [],
      explanation: ['maze = labyrinth', 'maize = corn'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Good surface, with spelling doing some of the work.',
    },
    {
      id: 'draft-035',
      clue: 'hotel confection',
      displayAnswer: 'suite sweet',
      answerWords: ['suite', 'sweet'],
      aliases: [],
      explanation: ['suite = hotel rooms / lodging set', 'sweet = confection / sugary treat'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Charming and accessible.',
    },
    {
      id: 'draft-036',
      clue: 'summit glance',
      displayAnswer: 'peak peek',
      answerWords: ['peak', 'peek'],
      aliases: [],
      explanation: ['peak = summit / top point', 'peek = glance / quick look'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Clean and satisfying.',
    },
    {
      id: 'draft-037',
      clue: 'fruit interment',
      displayAnswer: 'berry bury',
      answerWords: ['berry', 'bury'],
      aliases: [],
      explanation: ['berry = fruit', 'bury = inter / place underground'],
      difficulty: 'hard',
      status: 'draft',
      notes: 'A fair hard clue because the second half is less automatic.',
    },
    {
      id: 'draft-038',
      clue: 'function tumble',
      displayAnswer: 'role roll',
      answerWords: ['role', 'roll'],
      aliases: [],
      explanation: ['role = function / part', 'roll = tumble / turn over'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Simple but serviceable.',
    },
    {
      id: 'draft-039',
      clue: 'soared illness',
      displayAnswer: 'flew flu',
      answerWords: ['flew', 'flu'],
      aliases: [],
      explanation: ['flew = soared / traveled by air', 'flu = illness / influenza'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Silly but clean.',
    },
    {
      id: 'draft-040',
      clue: 'hesitation claws',
      displayAnswer: 'pause paws',
      answerWords: ['pause', 'paws'],
      aliases: [],
      explanation: ['pause = hesitation / stop briefly', 'paws = claws / animal feet'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Cute ending note to the expanded batch.',
    },
  ];
})(typeof globalThis !== 'undefined' ? globalThis : this);
