(function (root) {
  root.HOMONYM_DRAFT_PUZZLES = [
    {
      id: 'draft-001',
      clue: 'loathsome test tube',
      displayAnswer: 'vile vial',
      answerWords: ['vile', 'vial'],
      aliases: ['vile-vial'],
      explanation: ['vile = loathsome', 'vial = test tube / small lab bottle'],
      difficulty: 'easy',
      status: 'reviewed',
      notes: 'Still one of the cleanest model entries.',
    },
    {
      id: 'draft-002',
      clue: 'lazy golden calf',
      displayAnswer: 'idle idol',
      answerWords: ['idle', 'idol'],
      aliases: ['idle-idol'],
      explanation: ['idle = lazy', 'idol = golden calf / object of worship'],
      difficulty: 'easy',
      status: 'reviewed',
      notes: 'Strong flagship example for the core mechanic.',
    },
    {
      id: 'draft-003',
      clue: 'thief of shepherd\'s tools',
      displayAnswer: 'crook crook',
      answerWords: ['crook', 'crook'],
      aliases: [],
      explanation: ['crook = thief / criminal', 'crook = shepherd\'s hooked staff'],
      difficulty: 'medium',
      status: 'prototype',
      notes: 'Funny, but repeated-word answers may need to stay rare.',
    },
    {
      id: 'draft-004',
      clue: 'sad sunrise',
      displayAnswer: 'mourning morning',
      answerWords: ['mourning', 'morning'],
      aliases: [],
      explanation: ['mourning = grief / sadness', 'morning = sunrise time'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Very legible; phrase is a little literary but still natural enough.',
    },
    {
      id: 'draft-005',
      clue: 'navy belly button',
      displayAnswer: 'naval navel',
      answerWords: ['naval', 'navel'],
      aliases: [],
      explanation: ['naval = related to the navy', 'navel = belly button'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Sharp sound pair and compact clue.',
    },
    {
      id: 'draft-006',
      clue: 'only spirit',
      displayAnswer: 'sole soul',
      answerWords: ['sole', 'soul'],
      aliases: [],
      explanation: ['sole = only', 'soul = spirit / being'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Clean and intuitive.',
    },
    {
      id: 'draft-007',
      clue: 'dear woodland animal',
      displayAnswer: 'dear deer',
      answerWords: ['dear', 'deer'],
      aliases: [],
      explanation: ['dear = beloved', 'deer = woodland animal'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Very accessible; maybe slightly nursery-rhyme in tone.',
    },
    {
      id: 'draft-008',
      clue: 'faint seven days',
      displayAnswer: 'weak week',
      answerWords: ['weak', 'week'],
      aliases: [],
      explanation: ['weak = faint / lacking strength', 'week = seven days'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Simple and fair, though maybe too easy for the final daily set.',
    },
    {
      id: 'draft-009',
      clue: 'plain aircraft',
      displayAnswer: 'plain plane',
      answerWords: ['plain', 'plane'],
      aliases: [],
      explanation: ['plain = simple / unadorned', 'plane = aircraft'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Strong adjective + noun structure.',
    },
    {
      id: 'draft-010',
      clue: 'cereal murderer',
      displayAnswer: 'serial cereal',
      answerWords: ['serial', 'cereal'],
      aliases: [],
      explanation: ['serial = repeated / sequential', 'cereal = breakfast grain'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Absurdist but memorable.',
    },
    {
      id: 'draft-011',
      clue: 'principal belief',
      displayAnswer: 'principal principle',
      answerWords: ['principal', 'principle'],
      aliases: [],
      explanation: ['principal = chief / main', 'principle = belief / rule'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Educational and fair, but slightly abstract.',
    },
    {
      id: 'draft-012',
      clue: 'junior prospector',
      displayAnswer: 'minor miner',
      answerWords: ['minor', 'miner'],
      aliases: [],
      explanation: ['minor = junior / underage', 'miner = one who digs ore'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Very clean and concrete.',
    },
    {
      id: 'draft-013',
      clue: 'waistline garbage',
      displayAnswer: 'waist waste',
      answerWords: ['waist', 'waste'],
      aliases: [],
      explanation: ['waist = waistline / middle of the body', 'waste = garbage / refuse'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Compact and vivid.',
    },
    {
      id: 'draft-014',
      clue: 'manly post',
      displayAnswer: 'male mail',
      answerWords: ['male', 'mail'],
      aliases: ['mailed male'],
      explanation: ['male = manly / masculine', 'mail = post / letters'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Good sound pair, though the clue wording can probably improve.',
    },
    {
      id: 'draft-015',
      clue: 'permitted out loud',
      displayAnswer: 'allowed aloud',
      answerWords: ['allowed', 'aloud'],
      aliases: [],
      explanation: ['allowed = permitted', 'aloud = out loud'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Tight and self-explanatory.',
    },
    {
      id: 'draft-016',
      clue: 'vision location',
      displayAnswer: 'sight site',
      answerWords: ['sight', 'site'],
      aliases: [],
      explanation: ['sight = vision', 'site = place / location'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Fair but a bit abstract; may need a punchier clue.',
    },
    {
      id: 'draft-017',
      clue: 'blossom baking powder',
      displayAnswer: 'flower flour',
      answerWords: ['flower', 'flour'],
      aliases: [],
      explanation: ['flower = blossom', 'flour = baking powder / milled grain'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Very familiar sound pair and easy onboarding candidate.',
    },
    {
      id: 'draft-018',
      clue: 'couple fruit',
      displayAnswer: 'pair pear',
      answerWords: ['pair', 'pear'],
      aliases: [],
      explanation: ['pair = couple', 'pear = fruit'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Excellent for a beginner pack.',
    },
    {
      id: 'draft-019',
      clue: 'armored evening',
      displayAnswer: 'knight night',
      answerWords: ['knight', 'night'],
      aliases: [],
      explanation: ['knight = armored warrior', 'night = evening / darkness'],
      difficulty: 'easy',
      status: 'draft',
      notes: 'Simple and vivid, though slightly storybook in tone.',
    },
    {
      id: 'draft-020',
      clue: 'store corridor island',
      displayAnswer: 'aisle isle',
      answerWords: ['aisle', 'isle'],
      aliases: [],
      explanation: ['aisle = store corridor / passage', 'isle = island'],
      difficulty: 'medium',
      status: 'draft',
      notes: 'Clean sound pair; clue is compact but slightly clipped.',
    },
  ];
})(typeof globalThis !== 'undefined' ? globalThis : this);
